[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/root/.local/share/qBittorrent/logs

[BitTorrent]
Session\AddTorrentStopped=false
Session\DefaultSavePath=/mnt/torrents
Session\ExcludedFileNames=
Session\Port=1924
Session\QueueingSystemEnabled=false
Session\SSL\Port=32811
Session\ShareLimitAction=Stop
Session\TempPath=/torrents/temp
Session\TempPathEnabled=false

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()
PortForwardingEnabled=true
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
General\Locale=en
MailNotification\req_auth=true
WebUI\AuthSubnetWhitelist=192.168.10.0/24
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="@ByteArray(j98OG/8+R82qSMpdzLccng==:UcnCsuPfoGu8tCGDABQI8m2ciDUi4dQVv/e/wAyQpSZ57iBswcX2RCWmZ2Eni5wwr7hNUh/7dL9fJSYWpSQDBg==)"
WebUI\Port=8090
WebUI\UseUPnP=false
WebUI\Username=admin

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
